name: dartx
description: Superpowers for Dart. Collection of useful static extension methods.
version: 0.4.0
homepage: https://github.com/leisim/dartx

environment:
  sdk: ">=2.6.0-dev.5.0 <3.0.0"

dependencies:
  collection: ">=1.14.11 <1.15.0"
  path: ^1.6.2
  crypto: ">=2.1.0 <2.2.0"
  characters: ">=0.4.0 <1.0.0"
  time: ^1.2.0

dev_dependencies:
  test: ^1.9.2
  pedantic: ^1.8.0
  fake_async: ^1.1.0